
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: "Rains Blog"
subtitle: "Góc khuất của tôi"
email: trankhanha7@gmail.com
author: kioku17
avatar: https://i.imgur.com/GzMbPAW.jpg
quotes: "Tôi đang bắt đầu, với tất cả những gì vốn có..."
description: 
  I love blogger!

baseurl: "/" 
url: "https://root.rains.gq" 

# Build settings
markdown: kramdown
permalink: /:title
paginate: 10
paginate_path: "/page-:num/"
